# Generated by Django 4.0.2 on 2022-02-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
